require("heloint.lazy")
require("heloint.set")
require("heloint.theme")
-- require("heloint.ibl")
require("heloint.keymaps")
require("heloint.lsp")
require("heloint.cmp")
-- require("heloint.file_explorer")
require("heloint.treesitter")
require("heloint.telescope")
require("heloint.formatter")
require("heloint.autocmds")
require("heloint.comment")
require("heloint.my_quickfixlist")
require("heloint.my_terminal")
require("heloint.my_trailing_whitespaces")
require("heloint.my_wildignore")
require("heloint.my_formatter")
require("heloint.my_file_ops")
require("heloint.my_greps")

